name: Test
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Invoking test
        run: go test ./...